import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import mountain from '.././public/mountain.jpg'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Static web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.head_title_container}>
          <h1 className={styles.blog}>Blog.</h1>
          <p className={styles.right_text}>A statically generated blog example using {""}
          <a className={styles.nextjsLink}  href="https://nextjs.org/" >Next.js</a>
          </p>
        </div>
        <Image src={mountain}></Image>
      </main>

    </div>
  )
}

export default Home
